weights: ''
segcfg: models/yolov5s_seg4.yaml
data: datasets/steel_seg/steel_seg.yaml
hyp: ./data/hyps/hyp.scratch-med.yaml
epochs: 300
batch_size: 4
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 2
project: master/runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 0
freeze: 0
save_period: -1
local_rank: -1
noplots: false
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: master\runs\train\exp6
